config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  root to: "notifications#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :number])
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = user.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rakushif</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notifications/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%# = @room.name %>
    </div>
  </div>
  <div class="right-header">
  </div>
</div>

<div class="messages">
  <%# = render partial: 'message', collection: @messages %>
    <div class='notification-contents'>
    <h2 class='title'>申請一覧</h2>
    <div class="subtitle" >
    </div>
    <ul class='notification-lists'>

        <%#  @notifications.each do |notification| %>
          <li class='list'> 
            <%# = link_to notification_path(notification.id) do %>
              <div class='notification-number-content'>
                <%#= image_tag notification.image, class: "notification-img" %>
              </div>
            <%# end %>
          </li>
        <%# end %>
      
    </ul>
  </div>
</div>

app/views/notifications/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <a href="#">Tom</a>
  </div>
  <div class="create-room">
     <a href="#">チャットを作成する</a>
  </div>
</div>

<div class="rooms">
    <div class="room">
    <div class="room-name">
      <a href="#">techroom1</a>
    </div>
  </div>
  <div class="room">
    <div class="room-name">
      <a href="#">techroom2</a>
    </div>
  </div>
</div>

app/views/notifications/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>